# Generated by Django 5.0 on 2023-12-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibletext_app', '0002_greek_word_morphology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greek_Word',
        ),
    ]
