# Generated by Django 5.0 on 2023-12-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank_app', '0002_alter_wordbank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbank',
            name='id',
        ),
        migrations.AddField(
            model_name='wordbank',
            name='word_bank_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
