# Generated by Django 5.0 on 2023-12-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank_app', '0004_alter_wordbank_word_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='word_bank_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
