# Generated by Django 5.0 on 2023-12-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank_app', '0005_alter_wordbank_word_bank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbank',
            name='word_bank_id',
        ),
        migrations.AddField(
            model_name='wordbank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
