# Generated by Django 5.0 on 2023-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wordbank_app', '0006_remove_wordbank_word_bank_id_wordbank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greek_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default=None)),
                ('morphology', models.TextField(default=None)),
                ('word_bank', models.ManyToManyField(related_name='greekwords', to='wordbank_app.wordbank')),
            ],
        ),
    ]
