# Generated by Django 5.0 on 2023-12-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0001_initial'),
        ('wordbank_app', '0006_remove_wordbank_word_bank_id_wordbank_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greek_Word',
            new_name='GreekWord',
        ),
    ]
