# Generated by Django 5.0 on 2023-12-18 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0005_alter_greekword_word'),
        ('wordbank_app', '0006_remove_wordbank_word_bank_id_wordbank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greekword',
            name='word_bank',
        ),
        migrations.AddField(
            model_name='greekword',
            name='word_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='greekwords', to='wordbank_app.wordbank'),
            preserve_default=False,
        ),
    ]
