# Generated by Django 5.0 on 2023-12-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0006_remove_greekword_word_bank_greekword_word_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='morphology',
            field=models.TextField(default=None, null=True),
        ),
    ]
