# Generated by Django 5.0 on 2023-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0007_alter_greekword_morphology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='word',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
