# Generated by Django 5.0 on 2024-01-22 05:26

from django.db import migrations, models

# def set_default_chapter_number(apps, schema_editor):
#     def set_default_chapter_number(apps, schema_editor):
#         GreekWord = apps.get_model('greekword_app', 'GreekWord')
#         GreekWord.objects.filter(ChapterNumber__isnull=True).update(ChapterNumber='1')

# def set_default_verse_number(apps, schema_editor):
#     GreekWord = apps.get_model('greekword_app', 'GreekWord')
#     GreekWord.objects.filter(VerseNumber__isnull=True).update(VerseNumber='1')


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0008_alter_greekword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='greekword',
            name='ChapterNumber',
            field=models.CharField(default='Book', max_length=100),
        ),

        migrations.AddField(
            model_name='greekword',
            name='VerseNumber',
            field=models.CharField(default='1', max_length=100),
        ),

        migrations.AddField(
            model_name='greekword',
            name='bookId',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
