# Generated by Django 5.0 on 2024-01-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0009_greekword_chapternumber_greekword_versenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='ChapterNumber',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='VerseNumber',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='bookId',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
