# Generated by Django 5.0 on 2024-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0010_alter_greekword_chapternumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='ChapterNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='bookId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
