# Generated by Django 5.0 on 2024-01-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0011_alter_greekword_chapternumber_alter_greekword_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='ChapterNumber',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='bookId',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='morphology',
            field=models.TextField(default=None),
        ),
    ]
