# Generated by Django 5.0 on 2024-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0014_alter_greekword_chapternumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='morphology',
            field=models.TextField(default='Morphology'),
        ),
    ]
