# Generated by Django 5.0 on 2024-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0015_alter_greekword_morphology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='morphology',
            field=models.TextField(default='morphology'),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='word',
            field=models.CharField(default='word', max_length=100, unique=True),
        ),
    ]
