# Generated by Django 5.0 on 2024-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0016_alter_greekword_morphology_alter_greekword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greekword',
            name='ChapterNumber',
            field=models.CharField(default='chapter', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='VerseNumber',
            field=models.CharField(default='verse', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greekword',
            name='bookId',
            field=models.CharField(default='book', max_length=100, null=True),
        ),
    ]
