# Generated by Django 5.0 on 2024-01-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0017_alter_greekword_chapternumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greekword',
            old_name='ChapterNumber',
            new_name='chapterNumber',
        ),
        migrations.RenameField(
            model_name='greekword',
            old_name='VerseNumber',
            new_name='verseNumber',
        ),
    ]
