# Generated by Django 5.0 on 2023-12-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greekword_app', '0001_initial'),
        ('wordbank_app', '0002_alter_wordbank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greek_word',
            name='word_bank',
        ),
        migrations.AddField(
            model_name='greek_word',
            name='word_bank',
            field=models.ManyToManyField(related_name='greekwords', to='wordbank_app.wordbank'),
        ),
    ]
